import {app} from '../state.js';
import {audio} from '../audio.js';
import {showPanel,bind,start,gameplayUI,mainMenu} from '../ui/HUD.js';
export class EndingScene extends Phaser.Scene{
 constructor(){super('Ending');}
 create(data){app.current=this;app.mode='ending';app.paused=false;gameplayUI(false);audio.suspend(false);audio.music(5);audio.sfx('birthday');this.add.image(480,270,'world5').setDisplaySize(960,540);this.add.rectangle(480,490,960,100,0xeba0b8);const cake=this.add.image(760,485,'cake').setOrigin(.5,1).setScale(2.2);const sally=this.add.sprite(750,239,'sally').setOrigin(.5,1).setScale(2.5).play(data.kind==='story'?'sally-victory':'sally-birthday');this.add.text(755,83,'♥  SALLY  ♥',{fontSize:21,color:'#a2547f',fontStyle:'bold'}).setOrigin(.5);for(let i=0;i<42;i++){const r=this.add.rectangle((i*73)%960,-20-(i*57)%520,5+(i%3)*2,7,[0xf2a2bf,0xffe1a0,0x92cbbd,0xbb9cd1][i%4]);this.tweens.add({targets:r,y:560,x:r.x+30,duration:4000+(i%5)*500,repeat:-1,delay:i*40});}this.tweens.add({targets:sally,y:233,duration:600,yoyo:true,repeat:-1});this.tweens.add({targets:cake,alpha:.8,duration:1100,yoyo:true,repeat:-1});
 const birthday=data.kind==='birthday';const heading=birthday?'HAPPY BIRTHDAY SALLY!':data.kind==='dream'?'A DREAM FULL OF SMILES!':'SALLY BB SAVED THE DREAM WORLD!';const sub=birthday?'913 Birthday Stage Cleared!':data.superstar?'SALLY BB SUPER STAR!':'One tiny BB. One very big heart.';const extra=data.secret?'<p><b>You found Sally’s Secret Birthday Wish!</b><br>May every adventure ahead make you smile. ❤️</p>':data.superstar?'<p>All five letters found!<br><b>SECRET DREAM LEVEL unlocked ★</b></p>':birthday?`<p>Birthday treasures: ${data.count} / 18<br>Another wish is hiding in the party…</p>`:'';
 showPanel(`<div class="title-card ending-card"><div class="eyebrow">${birthday?'a wish just for you':'and they dreamed happily ever after'}</div><h1 style="font-size:clamp(22px,3.5vw,42px);line-height:1.1;color:#a9517b;margin:14px 0">${heading}</h1><p class="subtitle">${sub}</p>${extra}<p style="font-weight:800">Made especially for Sally ❤️<br>${birthday?'Happy Birthday!':'Game idea by Man Hin · Built with Phaser'}</p><div class="menu-actions">${data.superstar?'<button id="dream" class="primary">PLAY SECRET DREAM LEVEL ★</button>':''}<button id="party" class="primary">PLAY LEVEL 913 ♥</button><button id="menu">MAIN MENU</button></div><p class="footnote">SCORE ${data.score} · Special 913 Birthday Edition</p></div>`,true);bind('party',()=>start(5));bind('menu',mainMenu);bind('dream',()=>start(6));this.cameras.main.fadeIn(700,255,225,211);
 }
}
