import {app} from '../state.js';
import {save} from '../config.js';
import {audio} from '../audio.js';
import {showPanel,bind,start,gameplayUI} from '../ui/HUD.js';
export class MenuScene extends Phaser.Scene{
 constructor(){super('Menu');}
 create(){app.current=this;app.mode='menu';gameplayUI(false);audio.music(5);this.add.image(480,270,'world5').setDisplaySize(960,540);const g=this.add.graphics();g.fillStyle(0xedb0bb);g.fillRect(0,435,960,105);g.fillStyle(0xffe4bf);g.fillRect(0,435,960,9);for(let x=0;x<960;x+=32){g.fillStyle(0xdb91a9);g.fillRect(x,459,16,4);}g.lineStyle(3,0xb57e9a);g.beginPath();g.moveTo(460,20);g.lineTo(960,60);g.strokePath();for(let i=0;i<12;i++){const x=475+i*43,y=21+i*3.5;g.fillStyle([0xef9bb8,0xffd893,0xabe1d4][i%3]);g.fillTriangle(x,y,x+23,y+2,x+9,y+29);}
 this.add.image(758,399,'cake').setScale(1.75).setOrigin(.5,1);this.hero=this.add.sprite(720,423,'sally').setOrigin(.5,1).setScale(3.1).play('sally-idle');this.add.image(912,453,'present').setScale(.85).setOrigin(.5,1);this.add.image(570,454,'tree').setScale(.7).setOrigin(.5,1);this.add.text(697,135,'♥  913  ♥',{fontFamily:'Trebuchet MS',fontSize:25,color:'#b26288',fontStyle:'bold'}).setOrigin(.5);this.tweens.add({targets:this.hero,y:417,duration:1400,yoyo:true,repeat:-1,ease:'Sine.easeInOut'});for(let i=0;i<16;i++){const p=this.add.image(480+i*31,80+(i*67)%290,'item',i%2?3:4).setScale(.5).setAlpha(.6);this.tweens.add({targets:p,y:p.y-15,duration:900+i*70,yoyo:true,repeat:-1});}this.menu();}
 menu(){showPanel(`<div class="title-card"><div class="eyebrow">a little game · a lot of love</div><h1 class="logo">SALLY BB</h1><p class="subtitle">A Tiny BB. A Big Adventure.</p><span class="badge">Special 913 Birthday Edition</span><div class="menu-actions"><button class="primary" id="story">PLAY STORY MODE →</button><button id="birthday">♥ PLAY LEVEL 913</button>${save.story||save.dreamUnlocked?`<div class="mini-row">${save.story?'<button id="continue">CONTINUE STORY</button>':''}${save.dreamUnlocked?'<button id="dream">★ SECRET DREAM</button>':''}</div>`:''}<div class="mini-row"><button id="how">HOW TO PLAY</button><button id="sound">SOUND ${save.sound?'ON':'OFF'}</button><button id="credits">CREDITS</button></div></div><p class="footnote">Made especially for Sally ❤️<br>BEST ${String(save.best).padStart(6,'0')}${save.birthdaySecret?' · Birthday wish found ♥':''}</p></div>`,true);bind('story',()=>start(0));bind('birthday',()=>start(5));bind('continue',()=>start(save.story.level,true));bind('dream',()=>start(6));bind('how',()=>this.help());bind('credits',()=>this.credits());bind('sound',()=>{audio.toggle();this.menu();});}
 help(){showPanel(`<div class="menu-card"><div class="eyebrow">tiny steps, big smiles</div><h1>A little magic goes a long way</h1><div class="instructions"><div><b>◀ ▶ MOVE</b>Hold the arrows. Keyboard: A / D.</div><div><b>↑ JUMP</b>Tap or press Space. Release for a small hop.</div><div><b>♥ HEART RATTLE</b>Tap or press X to inflate a grumpy friend.</div><div><b>FLOAT & LAUNCH</b>Jump onto a balloon. Rattle again to launch it!</div></div><p>Find one hidden letter in each world to spell SALLY.<br>In Level 913, gather all 18 birthday gifts for a secret wish.</p><p class="footnote">Escape / Ⅱ pauses · F toggles fullscreen<br>↓ + Jump drops through ledges · Flags save your checkpoint<br>Safari: Share → Add to Home Screen for offline adventures.</p><div class="row"><button id="test" class="primary">♪ TEST SOUND</button><button id="motion">SHAKE ${save.reducedMotion?'OFF':'ON'}</button><button id="back">LET’S GO</button></div></div>`);bind('back',()=>this.menu());bind('test',()=>{if(!save.sound)audio.toggle();audio.sfx('birthday');});bind('motion',async()=>{const {persist}=await import('../config.js');save.reducedMotion=!save.reducedMotion;persist();document.querySelector('#motion').textContent=`SHAKE ${save.reducedMotion?'OFF':'ON'}`;});}
 credits(){showPanel(`<div class="menu-card"><div class="eyebrow">handmade with heart</div><h1>Made especially for Sally ❤️</h1><p>Game idea by <b>Man Hin</b><br>Built with Phaser 3<br>Original pixel art, levels, melodies & sound design.</p><p>Sally’s warm brown hair, cheerful smile, heart top,<br>pink skirt and white shoes inspired this tiny heroine.</p><p class="footnote">Sally BB · Special 913 Birthday Edition<br>Phaser © Phaser Studio, Inc. · MIT licence</p><div class="row"><button id="back" class="primary">BACK TO THE PARTY</button></div></div>`);bind('back',()=>this.menu());}
}
