import {WORLDS,save,persist,ITEM_NAMES} from '../config.js';
import {app} from '../state.js';
import {audio} from '../audio.js';
import {controls} from '../ui/TouchControls.js';
import {hud,toast,hidePanel,showPanel,bind,gameplayUI,mainMenu} from '../ui/HUD.js';
import {Sally} from '../entities/Sally.js';
import {Enemy} from '../entities/Enemy.js';

export class StoryScene extends Phaser.Scene{
 constructor(key='Story'){super(key);}
 create(data){this.level=data.level??0;this.isBoss=!!data.boss;this.world=WORLDS[this.level];this.mapWidth=this.isBoss?1500:this.world.length;this.elapsed=0;this.finished=false;this.health=data.run.health||3;this.stars=0;this.milkTimer=0;this.checkpoint={x:90,y:400};this.collected=new Set(data.run.collected||[]);this.birthdayCollected=new Set();this.birthdayTotal=18;this.dropPlatforms=[];this.movers=[];this.clouds=[];this.enemyList=[];this.fx=[];this.shots=[];this.hints=new Set();this.secretShown=false;this.levelSnapshot={...data.run,letters:[...data.run.letters],collected:[],health:3};app.run=data.run;app.current=this;app.mode='play';app.paused=false;hidePanel();gameplayUI(true);controls.reset();audio.suspend(false);audio.music(this.world.music);
 this.physics.world.setBounds(0,-200,this.mapWidth,1000);this.physics.world.resume();this.drawWorld();this.solids=this.physics.add.staticGroup();this.platforms=this.physics.add.group({allowGravity:false,immovable:true});this.enemies=this.physics.add.group({runChildUpdate:false});this.pickups=this.physics.add.staticGroup();this.makeMap();this.addGardenDetails();
 const cp=data.run.checkpoint;if(cp)this.checkpoint={...cp};this.player=new Sally(this,this.checkpoint.x,this.checkpoint.y);this.physics.add.collider(this.player,this.solids,(p,s)=>this.platformEffect(p,s));this.physics.add.collider(this.player,this.platforms,(p,s)=>this.platformEffect(p,s),(p,s)=>this.oneWay(p,s));this.physics.add.collider(this.enemies,this.solids,undefined,(e)=>e.state==='normal');this.physics.add.collider(this.enemies,this.platforms,undefined,(e,p)=>e.state==='normal'&&e.body.velocity.y>=0&&e.body.bottom<p.body.top+10);
 this.physics.add.collider(this.player,this.enemies,()=>{},(p,e)=>e.state==='floating'&&p.dropTimer<=0&&p.body.velocity.y>=0&&p.body.bottom<=e.body.top+15);
 this.physics.add.overlap(this.player,this.enemies,(p,e)=>{if(e.state==='normal')this.damage(e.x);});this.physics.add.overlap(this.player,this.pickups,(p,c)=>this.collect(c));
 this.cameras.main.setBounds(0,0,this.mapWidth,540);this.cameras.main.startFollow(this.player,true,.16,.16,-100,0);this.cameras.main.setDeadzone(30,540);this.cameras.main.roundPixels=true;this.goalX=this.mapWidth-170;this.goal=this.add.image(this.goalX,440,this.level===5||this.level===6?'cake':'arch').setOrigin(.5,1).setScale(this.level===5?1.65:1).setDepth(2);this.goal.setVisible(!this.isBoss);if(this.isBoss)this.makeBoss();hud(this);toast(this.isBoss?'Inflate the toys. Rattle them back at Nanny!':this.level===5?'For Sally ♥ Find all 18 birthday treasures.':`${this.level+1} / 5 · ${this.world.name}`);
 this.events.once('shutdown',()=>{controls.reset();for(const e of this.enemyList)e.bubble?.destroy();});
 }
 addGardenDetails(){const g=this.add.graphics().setDepth(2);for(let x=30;x<this.mapWidth;x+=86){if(this.solids.getChildren().some(s=>s.y>450&&x>s.x-s.width/2&&x<s.x+s.width/2)){if(this.level===1){g.fillStyle(0x679aa7);g.fillRect(x,450,26,9);g.fillStyle(0xfbe4b6);g.fillRect(x+4,452,4,4);}else{g.fillStyle(this.level===3?0xbab1d6:0x86b9a2);g.fillRect(x,422,3,13);g.fillRect(x-4,427,4,3);g.fillStyle([0xfff0cf,0xf8b7c8,0xffd99c][Math.floor(x/86)%3]);g.fillRect(x-3,415,9,7);g.fillRect(x-5,417,13,3);g.fillStyle(0xe5ad68);g.fillRect(x,417,3,3);}}}
 for(let x=75;x<this.mapWidth;x+=135){g.fillStyle(this.world.edge,.23);g.fillRect(x,475,14,4);g.fillRect(x+23,510,25,4);}
 if(this.level===5){for(const p of this.platforms.getChildren()){const x=p.x,y=p.y;if(p.kind==='bounce'){g.fillStyle(0xb0d9c5);g.fillRoundedRect(x-p.width/2,y-3,p.width,20,7);g.lineStyle(2,0xe5f2d7);g.strokeRoundedRect(x-p.width/2+2,y-5,p.width-4,10,6);}else{g.fillStyle(0xe7a1b9);g.fillRect(x-p.width/2,y+8,p.width,22);g.fillStyle(0xffe5bb);g.fillRect(x-p.width/2,y+16,p.width,6);for(let j=x-p.width/2+3;j<x+p.width/2;j+=18){g.fillStyle(0xfff0dc);g.fillCircle(j,y-6,9);}this.add.sprite(x,y-24,'item',7).setDepth(0);}}
 for(let x=520;x<this.mapWidth;x+=570){this.add.image(x,437,'present').setScale(.48).setOrigin(.5,1).setDepth(0);this.add.sprite(x+75,145,'item',9).setScale(2.5).setAlpha(.8).setDepth(-1);g.lineStyle(1,0xb6899f);g.lineBetween(x+75,165,x+70,290);}const bridge=this.add.graphics().setDepth(0);bridge.lineStyle(6,0xf1b1c2);bridge.lineBetween(2150,400,2350,400);bridge.lineStyle(2,0xffe2b0);bridge.lineBetween(2150,398,2350,398);}
 }
 drawWorld(){this.add.tileSprite(0,0,this.mapWidth,540,'world'+this.world.sky).setOrigin(0).setTileScale(2).setScrollFactor(.32,0).setDepth(-5);const g=this.add.graphics().setDepth(-3);for(let x=80;x<this.mapWidth;x+=310){const decoration=this.level===2?'present':this.level===5?'cake':this.level===4||this.level===6?'arch':this.level===1?'present':'tree';this.add.image(x,439,decoration).setOrigin(.5,1).setScale(.65+(x%5)*.035).setAlpha(this.level===3?.35:.72).setDepth(-2);if(this.level===5){g.lineStyle(2,0xb87995);g.lineBetween(x-120,80,x+110,105);for(let i=0;i<7;i++){g.fillStyle([0xf7afc2,0xffd890,0xabd9cb][i%3]);g.fillTriangle(x-115+i*33,82+i*3.5,x-90+i*33,84+i*3.5,x-104+i*33,103+i*3.5);}}}
 }
 block(x,y,w,h=20,options={}){const color=options.bounce?0xa9d5c3:options.conveyor?0x89b5c4:this.world.floor;const r=this.add.rectangle(x+w/2,y+h/2,w,h,color).setDepth(1);r.setStrokeStyle(2,this.world.edge);this.physics.add.existing(r,!options.moving&&!options.cloud&&!options.oneWay);r.kind=options.bounce?'bounce':options.conveyor?'conveyor':'solid';r.direction=options.direction||1;r.oneWay=options.oneWay||options.moving||options.cloud;r.baseX=r.x;r.baseY=r.y;r.travel=options.travel||65;r.period=options.period||2.1;r.locked=options.locked||false;r.cloud=options.cloud||false;
 if(r.body instanceof Phaser.Physics.Arcade.Body){r.body.setAllowGravity(false);r.body.setImmovable(true);r.body.checkCollision.up=true;r.body.checkCollision.down=false;r.body.checkCollision.left=false;r.body.checkCollision.right=false;this.platforms.add(r);if(options.moving)this.movers.push(r);if(options.cloud)this.clouds.push(r);}else this.solids.add(r);
 const top=this.add.rectangle(r.x,y+3,w-4,5,options.bounce?0xdff4dd:0xfff0d8).setDepth(2);r.trim=top;for(let px=x+12;px<x+w;px+=28){const s=this.add.rectangle(px,y+11,6,3,this.world.edge,.55).setDepth(2);r.decor=r.decor||[];r.decor.push(s);}return r;}
 makeMap(){if(this.isBoss){this.block(0,435,this.mapWidth,105);return;}
 const gaps=this.level===0?[[940,1060],[2290,2420]]:this.level===5?[[900,1030],[2180,2310],[2920,3060]]:[[850,990],[2200,2350]];let last=0;for(const [a,b] of gaps){this.block(last,435,a-last,105);last=b;}this.block(last,435,this.mapWidth-last,105);
 const ledges=[[370,345,150],[660,315,145],[1110,340,145],[1360,325,140],[1530,265,135],[1690,205,150],[1880,300,140],[2050,355,130],[2460,345,160],[2690,290,145],[3100,340,135]];
 for(let i=0;i<ledges.length;i++){let [x,y,w]=ledges[i];if(x+w>this.mapWidth-280)continue;const options={oneWay:true};if(this.level===1&&i===2){options.moving=true;options.locked=true;options.travel=60;options.period=1.4;}if(this.level===1&&i===7)options.conveyor=true;if(this.level===2&&(i===0||i===7))options.bounce=true;if(this.level===2&&i===3){options.moving=true;options.vertical=true;options.travel=48;}if(this.level===3&&(i===1||i===4||i===8))options.cloud=true;if(this.level===3&&(i===2||i===6)){options.moving=true;options.vertical=true;options.travel=22;}if(this.level===5&&(i===0||i===7))options.bounce=true;const r=this.block(x,y,w,18,options);r.vertical=!!options.vertical;if(options.cloud){this.add.text(x+w/2,y-12,'☁',{fontSize:24,color:'#fff1e0'}).setOrigin(.5).setDepth(0);}}
 if(this.level===1){this.switch=this.add.rectangle(730,410,28,30,0xc2769e).setStrokeStyle(3,0xffe5ac);this.add.text(730,380,'♥ SWITCH',{fontSize:11,color:'#6c4a6b',fontStyle:'bold'}).setOrigin(.5);}
 for(let x=280,i=0;x<this.mapWidth-230;x+=225,i++){const type=(this.level+i)%7;this.addPickup(x,393,i%4===3?'star':i%3===2?'candy':'strawberry','food-'+i);if(i%3===1){const nearby=ledges.find(l=>Math.abs(l[0]+l[2]/2-x)<160);if(nearby)this.addPickup(nearby[0]+60,nearby[1]-30,'cake','cake-'+i);}}
 this.addPickup(1210,306,'heart','heal');this.addPickup(2580,305,'milk','milk');
 if(this.level<5){this.addPickup(1760,173,'letter','letter-'+this.level,this.level);this.add.text(1480,387,'A secret up above… ★',{fontSize:12,color:this.level===3?'#f9e8c5':'#91607b',fontStyle:'bold'}).setOrigin(.5);}
 if(this.level===5){const xs=[320,440,640,735,1120,1220,1380,1550,1740,1900,2060,2400,2500,2750,3110,3230,3410,3500];const ys=[394,310,394,278,309,394,291,230,170,269,324,394,310,254,306,394,394,394];for(let i=0;i<xs.length;i++)this.addPickup(xs[i],ys[i],['candle','cake','heart','gift','note','balloon'][i%6],'birthday-'+i,null,true);}
 const types=this.level===0?[0,2,5]:this.level===1?[3,4,2]:this.level===2?[1,3,2]:this.level===3?[6,4,2]:[0,1,5,4];for(let x=560,i=0;x<this.mapWidth-280;x+=340,i++){if(gaps.some(([a,b])=>x>a-45&&x<b+45))continue;const type=types[i%types.length];this.spawnEnemy(x,type===4||type===6?330:433,type);}
 for(const x of [1260,2520]){if(x<this.mapWidth-250){const g=this.add.graphics().setDepth(2);g.fillStyle(0xb78099);g.fillRect(x,377,4,59);g.fillStyle(0xffdca6);g.fillTriangle(x+4,377,x+36,388,x+4,401);this.add.text(x+8,380,'♥',{fontSize:12,color:'#bd6d91'});}}
 if(this.level===0){this.add.text(290,270,'↑ JUMP',{fontSize:13,color:'#a0647e',fontStyle:'bold'}).setOrigin(.5);this.add.text(610,245,'♥ RATTLE → FLOAT → RATTLE!',{fontSize:12,color:'#a0647e',fontStyle:'bold'}).setOrigin(.5);}
 }
 addPickup(x,y,kind,id,letter=null,birthday=false){if(this.collected.has(id)){if(birthday)this.birthdayCollected.add(id);return;}let c;if(kind==='letter'){c=this.add.text(x,y,'SALLY'[letter],{fontFamily:'Trebuchet MS',fontSize:24,fontStyle:'bold',color:'#fff1d3',stroke:'#b96691',strokeThickness:5}).setOrigin(.5);}else c=this.add.sprite(x,y,'item',ITEM_NAMES.indexOf(kind)).setScale(birthday?1.25:1);this.physics.add.existing(c,true);this.pickups.add(c);c.kind=kind;c.id=id;c.letter=letter;c.birthday=birthday;c.baseY=y;c.setDepth(4);}
 spawnEnemy(x,y,type,object=false){const e=new Enemy(this,x,y,type,object);this.enemies.add(e);this.enemyList.push(e);return e;}
 oneWay(p,s){return p.dropTimer<=0&&s.body.enable&&p.body.velocity.y>=0&&p.body.bottom<=s.body.top+12;}
 platformEffect(p,s){if(p.body.velocity.y<0)return;if(s.kind==='bounce'){p.setVelocityY(-650);audio.sfx('jump');this.burst(p.x,s.y,0xa6decc,6);}if(s.kind==='conveyor')p.x+=s.direction*1.8;}
 rattle(){audio.sfx('attack');const p=this.player;const pulse=this.add.sprite(p.x+p.face*30,p.y-32,'item',4).setDepth(9);this.fx.push({sprite:pulse,life:.32,vx:p.face*390,vy:0,scale:1});this.burst(p.x+p.face*30,p.y-30,0xffaaca,5);for(const e of this.enemyList){if(!e.active)continue;const dx=e.x-p.x;if(dx*p.face>=-28&&dx*p.face<160&&Math.abs((e.y-20)-(p.y-28))<65){if(e.state==='normal')e.inflate();else if(e.state==='floating')e.launch(p.face);}}
 if(this.switch&&Math.abs(p.x-this.switch.x)<110){this.switch.setFillStyle(0x9fcebd);this.movers.forEach(m=>m.locked=false);audio.sfx('switch');toast('Factory lift switched on!');}}
 collect(c){if(!c.active)return;this.collected.add(c.id);if(c.birthday){this.birthdayCollected.add(c.id);audio.sfx('collect');toast(`Birthday treasures ${this.birthdayCollected.size} / ${this.birthdayTotal} ♥`);if(this.birthdayCollected.size===this.birthdayTotal){this.secretShown=true;save.birthdaySecret=true;persist();audio.sfx('secret');this.burst(this.player.x,this.player.y-50,0xffd886,22);toast('You found Sally’s Secret Birthday Wish!');}}
 else if(c.kind==='letter'){if(!app.run.letters.includes(c.letter))app.run.letters.push(c.letter);app.run.letters.sort();save.letters=[...app.run.letters];save.story={...app.run,level:this.level,health:this.health,checkpoint:this.checkpoint,collected:[...this.collected],letters:[...app.run.letters]};persist();audio.sfx('secret');toast(`★ ${app.run.letters.map(i=>'SALLY'[i]).join('')} · Hidden letter found!`);}
 else if(c.kind==='heart'){this.health=Math.min(3,this.health+1);audio.sfx('heal');}
 else{const points={strawberry:100,candy:200,cake:300,star:500,milk:250,note:250}[c.kind]||100;app.run.score+=points;if(c.kind==='star')this.stars++;if(c.kind==='milk'){this.milkTimer=8;toast('Milk magic! Faster feet & a golden glow.');audio.sfx('heal');}else audio.sfx('collect');this.floatText(c.x,c.y,'+'+points);}
 this.player.pose='collect';this.player.poseTimer=.15;this.burst(c.x,c.y,0xffe2a6,7);c.destroy();hud(this);}
 floatText(x,y,label){const t=this.add.text(x,y,label,{fontSize:14,color:'#fff2cc',stroke:'#98517a',strokeThickness:3,fontStyle:'bold'}).setOrigin(.5).setDepth(10);this.fx.push({sprite:t,life:.7,vx:0,vy:-35});}
 burst(x,y,color,n=8){for(let i=0;i<n;i++){const s=this.add.rectangle(x,y,4+(i%2)*2,4,color).setDepth(10);this.fx.push({sprite:s,life:.4+(i%3)*.15,vx:Math.cos(i*2.4)*90,vy:Math.sin(i*2.4)*90-30});}}
 hostile(x,y,vx,vy){const s=this.physics.add.sprite(x,y,'item',this.level===3?3:1).setScale(.65).setDepth(7);s.body.setAllowGravity(true);s.setVelocity(vx,vy);this.shots.push({sprite:s,life:3});}
 damage(from){if(this.player.invincible>0||this.finished)return;this.health--;hud(this);audio.sfx('hurt');this.player.invincible=1.5;this.player.pose='hurt';this.player.poseTimer=.22;this.player.setVelocityY(-180);this.player.x+=(this.player.x<from?-1:1)*16;if(!save.reducedMotion&&!matchMedia('(prefers-reduced-motion: reduce)').matches)this.cameras.main.shake(90,.002);if(this.health<=0)this.gameOver();}
 gameOver(){save.best=Math.max(save.best,app.run.score);persist();this.finished=true;this.physics.world.pause();this.player.setAlpha(1).play('sally-over');app.mode='gameover';controls.reset();audio.suspend(true);showPanel(`<div class="menu-card"><div class="eyebrow">every adventure has another chance</div><h1>A tiny tumble ♥</h1><p>Take a breath, Sally. You’ve got this.</p><div class="row"><button id="retry" class="primary">RETRY LEVEL</button><button id="menu">MAIN MENU</button></div></div>`);bind('retry',()=>this.restart());bind('menu',mainMenu);}
 restart(){app.paused=false;audio.suspend(false);app.run={...this.levelSnapshot,letters:[...this.levelSnapshot.letters],health:3,collected:[],checkpoint:null};this.scene.restart({level:this.level,boss:this.isBoss,run:app.run});}
 checkpointSave(x){this.checkpoint={x:x+40,y:390};if(this.level<5){app.run.health=this.health;save.story={...app.run,level:this.level,checkpoint:this.checkpoint,collected:[...this.collected],letters:[...app.run.letters]};persist();}audio.sfx('heal');toast('Checkpoint ♥ Your adventure is safe.');}
 update(time,delta){if(app.paused||app.orientationPaused||this.finished)return;const dt=Math.min(delta,34)/1000;this.elapsed+=dt;this.milkTimer=Math.max(0,this.milkTimer-dt);this.player.tick(dt);this.cameras.main.setFollowOffset(-80*this.player.face,0);for(const m of this.movers){if(m.locked)continue;const oldX=m.x;const v=Math.sin(this.elapsed/m.period)*m.travel;m.x=m.vertical?m.baseX:m.baseX+v;m.y=m.vertical?m.baseY+v:m.baseY;const dx=m.x-oldX;if(this.player.body.bottom>=m.body.top-5&&this.player.body.bottom<=m.body.top+10&&Math.abs(this.player.x-m.x)<m.width/2)this.player.x+=dx;m.body.updateFromGameObject();m.trim.setPosition(m.x,m.y-m.height/2+3);if(m.decor)for(const s of m.decor)s.setVisible(false);}
 for(const c of this.clouds){const on=(this.elapsed+c.baseX/200)%4<3;c.body.enable=on;c.setAlpha(on?.8:.18);c.trim.setAlpha(on?.8:.18);c.decor?.forEach(s=>s.setAlpha(on?.5:.1));}
 for(const e of this.enemyList)if(e.active){e.tick(dt);if(e.y>650)e.pop();if(e.state==='launched'){for(const other of this.enemyList)if(other.active&&other!==e&&other.state==='normal'&&Math.abs(e.x-other.x)<35&&Math.abs(e.y-other.y)<40){other.pop();app.run.score+=400;audio.sfx('defeat');}if(this.isBoss&&this.bossHp>0&&Math.abs(e.x-this.boss.x)<72&&Math.abs(e.y-(this.boss.y-40))<115){this.hitBoss();e.pop();}}}
 this.enemyList=this.enemyList.filter(e=>e.active);
 for(const f of this.fx){f.life-=dt;f.sprite.x+=f.vx*dt;f.sprite.y+=f.vy*dt;f.sprite.setAlpha(Math.min(1,f.life*3));if(f.life<=0)f.sprite.destroy();}this.fx=this.fx.filter(f=>f.life>0);
 for(const s of this.shots){s.life-=dt;if(s.sprite.active&&Math.abs(s.sprite.x-this.player.x)<22&&Math.abs(s.sprite.y-(this.player.y-26))<30){this.damage(s.sprite.x);s.life=0;}if(s.life<=0)s.sprite.destroy();}this.shots=this.shots.filter(s=>s.life>0);
 if(this.player.y>600){this.damage(this.player.x+1);if(!this.finished){this.player.body.reset(this.checkpoint.x,this.checkpoint.y);this.player.invincible=1.5;}}
 for(const x of [1260,2520])if(x<this.mapWidth-250&&this.player.x>x&&!this.hints.has('cp'+x)){this.hints.add('cp'+x);this.checkpointSave(x);}
 if(this.isBoss)this.tickBoss(dt);if(this.finished)return;
 this.physics.world.update(time,Math.min(delta,34));hud(this);if(this.secretShown&&!this.wishPresented){this.wishPresented=true;this.birthdayWish();return;}if(!this.isBoss&&this.player.x>this.goalX-34&&this.player.y<470)this.clear();
 }
 birthdayWish(){app.paused=true;app.mode='wish';this.physics.world.pause();controls.reset();this.player.play('sally-birthday');this.cameras.main.flash(650,255,232,216);for(let i=0;i<18;i++){const s=this.add.sprite(this.player.x-120+(i*47)%240,this.player.y-20-(i*19)%90,'item',i%2?3:4).setDepth(15).setScale(.7);this.tweens.add({targets:s,y:s.y-160,alpha:0,duration:2200+(i%3)*400,onComplete:()=>s.destroy()});}showPanel(`<div class="menu-card"><div class="eyebrow">a little secret, just for Sally</div><h1>Sally’s Secret Birthday Wish ♥</h1><p><b>You found Sally’s Secret Birthday Wish!</b></p><p>May every adventure ahead make you smile. ❤️</p><div class="row"><button id="wish" class="primary">MAKE A WISH & KEEP GOING →</button></div></div>`);bind('wish',()=>{app.paused=false;app.mode='play';this.physics.world.resume();hidePanel();controls.reset();});}
 clear(){if(this.finished)return;this.finished=true;this.physics.world.pause();controls.reset();this.player.setVelocity(0,0).play(this.level===5?'sally-birthday':'sally-clear');audio.sfx(this.level===5?'birthday':'clear');save.best=Math.max(save.best,app.run.score);app.run.health=this.health;if(this.level===5){if(this.birthdayCollected.size===this.birthdayTotal)save.birthdaySecret=true;persist();this.scene.start('Ending',{kind:'birthday',secret:save.birthdaySecret&&this.birthdayCollected.size===this.birthdayTotal,count:this.birthdayCollected.size,score:app.run.score});return;}if(this.level===6){persist();this.scene.start('Ending',{kind:'dream',score:app.run.score});return;}
 if(this.level===4&&!this.isBoss){app.run.collected=[];app.run.checkpoint=null;this.scene.start('Boss',{level:4,boss:true,run:app.run});return;}
 const next=this.level+1;save.unlocked=Math.max(save.unlocked,next+1);app.run.level=next;app.run.collected=[];app.run.checkpoint=null;save.story={...app.run,letters:[...app.run.letters]};save.letters=[...app.run.letters];persist();app.mode='clear';showPanel(`<div class="menu-card"><div class="eyebrow">a little braver, a little brighter</div><h1>${this.world.name} cleared! ♥</h1><p>Next adventure: <b>${WORLDS[next].name}</b><br>Letters: ${app.run.letters.map(i=>'SALLY'[i]).join('')||'Still waiting to be found'} · Score ${app.run.score}</p><div class="row"><button id="next" class="primary">NEXT WORLD →</button><button id="menu">MAIN MENU</button></div></div>`);bind('next',()=>this.scene.restart({level:next,run:app.run}));bind('menu',mainMenu);}
 makeBoss(){this.bossHp=9;this.bossPhase=1;this.bossClock=1.6;this.bossInv=0;this.boss=this.add.image(1180,435,'nanny').setOrigin(.5,1).setScale(1.12).setDepth(6);this.bossBar=this.add.text(480,70,'',{fontSize:14,color:'#a6537b',fontStyle:'bold',backgroundColor:'#fff2dd'}).setOrigin(.5).setScrollFactor(0).setPadding(8,4);this.add.text(850,270,'♥ Inflate a toy, then face Nanny & rattle again.',{fontSize:13,color:'#955779',fontStyle:'bold'}).setOrigin(.5);}
 tickBoss(dt){if(this.bossHp<=0)return;this.bossInv=Math.max(0,this.bossInv-dt);this.boss.setAlpha(this.bossInv>0?.55:1);this.bossPhase=this.bossHp>6?1:this.bossHp>3?2:3;this.bossClock-=dt;this.bossBar.setText(`THE GRUMPY NANNY  ·  PHASE ${this.bossPhase}  ${'♥'.repeat(this.bossHp)}`);if(this.bossPhase===3){this.boss.x+=Math.sign(this.player.x-this.boss.x)*55*dt;this.boss.x=Phaser.Math.Clamp(this.boss.x,650,1350);}if(Math.abs(this.player.x-this.boss.x)<62&&this.player.y>300)this.damage(this.boss.x);if(this.bossClock<=0){this.bossClock=this.bossPhase===1?2.4:2;const type=this.bossPhase===2?4:1;const e=this.spawnEnemy(this.boss.x-95,410,type,true);e.body.setAllowGravity(true);e.dir=-1;e.setVelocity(-110,-(this.bossPhase===1?220:160));} }
 hitBoss(){if(this.bossInv>0)return;this.bossHp--;this.bossInv=.65;audio.sfx('hurt');this.burst(this.boss.x,this.boss.y-70,0xffd3ac,18);if(this.bossHp<=0){this.enemyList.forEach(e=>e.active&&e.pop());this.bossBar.destroy();this.boss.setTint(0xffd5e4);app.run.score+=3000;save.best=Math.max(save.best,app.run.score);save.story=null;save.unlocked=5;if(app.run.letters.length===5)save.dreamUnlocked=true;save.letters=[...app.run.letters];persist();this.finished=true;this.physics.world.pause();this.scene.start('Ending',{kind:'story',superstar:app.run.letters.length===5,score:app.run.score});}}
}
